<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <xacro:property name="lidar_size" value="0.1" /> <!-- 0.1 => 0.05 -->
    <xacro:property name="camera_size" value="0.2" /> <!-- 0.2 => 0.05 -->

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0 + wheel_radius}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0 + wheel_radius}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0 + wheel_radius}" rpy="0 0 0" />
        </collision>
    </link>

  <xacro:macro name="throttle_wheel_link" params="prefix">
      <link name="${prefix}_throttle_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="blue" />
        </visual>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
      </link>
  </xacro:macro>
  <xacro:macro name="steering_wheel_link" params="prefix">
      <link name="${prefix}_steering_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius/10}" length="${wheel_length/10}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="gray" />
        </visual>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius/10}" length="${wheel_length/10}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
      </link>
  </xacro:macro>

  <xacro:throttle_wheel_link prefix="l1" />
  <xacro:throttle_wheel_link prefix="l2" />
  <xacro:throttle_wheel_link prefix="l3" />
  
  <xacro:throttle_wheel_link prefix="r1" />
  <xacro:throttle_wheel_link prefix="r2" />
  <xacro:throttle_wheel_link prefix="r3" />

  <xacro:steering_wheel_link prefix="l3" />
  <xacro:steering_wheel_link prefix="r3" />

</robot>